### ISSUE TITLE
Remove all bibtex warnings

### ISSUE THREAD

**Issue by MLopez-Ibanez** [iridia-ulb/references#1]
Currently we produce the following bibtex warnings. These warnings may hide new warnings being introduced that detect actual issues. It would be good to fix these warnings by adding the missing editors or organizations, then make travis fail if new warnings appear.

Warning--to sort, need author, editor, or key in CCIE2010
Warning--to sort, need author, editor, or key in CEC1999
Warning--to sort, need author, editor, or key in CEC2000
Warning--to sort, need author, editor, or key in CEC2001
Warning--to sort, need author, editor, or key in CEC2002
Warning--to sort, need author, editor, or key in CEC2003
Warning--to sort, need author, editor, or key in CEC2004
Warning--to sort, need author, editor, or key in CEC2005
Warning--to sort, need author, editor, or key in CEC2006
Warning--to sort, need author, editor, or key in CEC2007
Warning--to sort, need author, editor, or key in CEC2008
Warning--to sort, need author, editor, or key in CEC2009
Warning--to sort, need author, editor, or key in CEC2011
Warning--to sort, need author, editor, or key in CEC2012
Warning--to sort, need author, editor, or key in CEC2013
Warning--to sort, need author, editor, or key in CEC2014
Warning--to sort, need author, editor, or key in CEC2015
Warning--to sort, need author, editor, or key in CEC2016
Warning--to sort, need author, editor, or key in CEC2017
Warning--to sort, need editor, organization, or key in CGO2008
Warning--to sort, need author, editor, or key in CP2002
Warning--to sort, need editor, organization, or key in EALS2014
Warning--to sort, need editor, organization, or key in ESANN2014
Warning--to sort, need editor, organization, or key in ESANN2015
Warning--to sort, need author, editor, or key in EVOPROG98
Warning--to sort, need editor, organization, or key in FMCAD2007
Warning--to sort, need editor, organization, or key in FOCS2000
Warning--to sort, need author, editor, or key in FOGA1996
Warning--to sort, need author, editor, or key in ICANNGA1999
Warning--to sort, need editor, organization, or key in ICAPS-PAL2011
Warning--to sort, need editor, organization, or key in ICML1994
Warning--to sort, need editor, organization, or key in ICML2008
Warning--to sort, need editor, organization, or key in ICML2010
Warning--to sort, need editor, organization, or key in ICML2014
Warning--to sort, need editor, organization, or key in ICMLC2004
Warning--to sort, need editor, organization, or key in ICMLC2006
Warning--to sort, need editor, organization, or key in IJCAI2001
Warning--to sort, need editor, organization, or key in ISDA2005
Warning--to sort, need editor, organization, or key in MIC1997
Warning--to sort, need editor, organization, or key in MIC2013
Warning--to sort, need editor, organization, or key in MIC2015
Warning--to sort, need editor, organization, or key in NAFIPS2002
Warning--to sort, need author, editor, or key in NICSO2009
Warning--to sort, need editor, organization, or key in PACT2014
Warning--to sort, need editor, organization, or key in PDP2011
Warning--to sort, need author, editor, or key in SIGKDD2000
Warning--to sort, need editor, organization, or key in SSCI2016
Warning--to sort, need author, editor, or key in WCCI1994
Warning--to sort, need author, editor, or key in WCCI2002
Warning--empty author and editor in WCCI1994
Warning--empty author and editor in FOGA1996
Warning--empty author and editor in EVOPROG98
Warning--empty author and editor in CEC1999
Warning--empty author and editor in ICANNGA1999
Warning--empty author and editor in CEC2000
Warning--empty author and editor in SIGKDD2000
Warning--empty author and editor in CEC2001
Warning--empty author and editor in CEC2002
Warning--empty author and editor in CP2002
Warning--empty author and editor in WCCI2002
Warning--empty author and editor in CEC2003
Warning--empty author and editor in CEC2004
Warning--empty author and editor in CEC2005
Warning--empty author and editor in CEC2006
Warning--empty author and editor in CEC2007
Warning--empty author and editor in CEC2008
Warning--empty author and editor in CEC2009
Warning--empty author and editor in NICSO2009
Warning--empty author and editor in CCIE2010
Warning--empty author and editor in CEC2011
Warning--empty author and editor in CEC2012
Warning--empty author and editor in CEC2013
Warning--empty author and editor in CEC2014
Warning--empty author and editor in CEC2015
Warning--empty author and editor in CEC2016
Warning--empty author and editor in CEC2017

**Comment by albertofranzin** [comment]
Editors for at least some conference proceedings seems to be quite hard to find. If that's mandatory, this will remain open for quite a while. Until then, I would not make travis halt on warnings.

Many of them are proceedings classified as books, that's easy to fix but will just change the warning.

With proceedings it is possible to add a `key` field that will be used when listing them (not the same thing of the entry key). I did a test and added a `key` to CEC 201{5,6,7}, now they appear in testbib.pdf and not in the warnings, but with the keys in the author place, which seems rather bad. The bibtex documentation is quite fuzzy and does not help much.

Using `organization = {{IEEE}}` results in

> [1072] Proceedings of the 2014 Congress on Evolutionary Computation (CEC 2014), Piscataway,
> NJ, 2014. IEEE, IEEE Press.

Provided that adding the editors is the best way of fixing the warning, is this workaround good enough?

**Comment by MLopez-Ibanez** [comment]
I think there are editors for most conferences (they are the general chairs or editors-in-chief). However, using a key is fine until someone bothers to add the editors,  but it should be something that looks OK. Like "IEEE CEC 2015". I don't like using the organization field unless it is not already in the title of the conference and there is no publisher.

**Comment by MLopez-Ibanez** [comment]
Note that proceedings published by a publisher are books.

**Comment by albertofranzin** [comment]
> I think there are editors for most conferences (they are the general chairs or editors-in-chief). 

For some (e.g. ACM ones) yes, but IEEE conferences like to keep secrets. Maybe "Editor in chief and others" is a good compromise between listing the editors, not having to wild guess the number of editors included, maintaining consistency with other entries and spending the right amount of time.

> However, using a key is fine until someone bothers to add the editors, but it should be something that looks OK. Like "IEEE CEC 2015". I don't like using the organization field unless it is not already in the title of the conference and there is no publisher.

ok.

> Note that proceedings published by a publisher are books.

in crossref.bib both are used. But `key` works only with proceedings.

**Comment by MLopez-Ibanez** [comment]
All warnings are fixed and travis now checks for warnings.
