### ISSUE TITLE
Move deploy from travis-ci to github actions

### ISSUE THREAD

**Issue by albertofranzin** [iridia-ulb/references#10]
Last November, travis-ci deployed a new pricing model, eliminating the free accounts https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

I just checked the account that does the continuous integration for this repo, we've been automatically transferred to the "free" trial account which includes 10000 credits, which allow for ~1000 minutes of computation on linux machines. When we'll run out of credits, we'll have to buy new ones. 

We still have plenty of credits (at the current rate, enough for the next 3 years), so it is not urgent at all. But maybe we can start considering alternatives?

**Comment by MLopez-Ibanez** [comment]
Definitely. If we can move to github actions, that would be great. Unfortunately, I don't have much experience with github actions, so if you know how, just go ahead and do it! :-)

**Comment by albertofranzin** [comment]
Cool, I'm learning now about github actions :)

Ok, I'll try to figure it out. Apparently there are tools for that https://github.com/marketplace/actions/github-action-for-latex I'll check this out when I have a bit of time.

**Comment by MLopez-Ibanez** [comment]
Thanks! It is possible to have both in parallel for a time, so feel free to experiment.

**Comment by MLopez-Ibanez** [comment]
I worked on this a bit. These are the things that need still some work:

- [ ] TRAVIS_COMMIT_RANGE: I copied some code found online but the output doesn't look correct to me. It includes too many commits.
- [ ] ./travis_test.sh uses travis-specific stuff. Convert those things to the equivalent for actions.
- [ ] ./travis_deploy.sh is not run yet. Some of the stuff there is travis-specific. Perhaps there are better (shorter) ways to do what this script does.

**Comment by MLopez-Ibanez** [comment]
The main remaining obstacles is travis_deploy.sh. The rest is already converted.

**Comment by MLopez-Ibanez** [comment]
I have removed travis_deploy.sh. Now we save the generated pdf files to the gh-pages branch. This way we also avoid large files in the master branch.

**Comment by MLopez-Ibanez** [comment]
Fixed in 4bfa40a3d572cbe0533e9b984f003a3e44dfb74e
