### ISSUE TITLE
crossref EuroGP2017 in 'CarPinOli2017recipe' doesn't match case of key EUROGP2017

### ISSUE THREAD

**Issue by GeoBosh** [iridia-ulb/references#7]
The following entries from files 'crossref.bib' and 'biblio.bib', respectively, use different capitalisation for key EUROGP2017:
```
@Book{EUROGP2017,
  ...
  booktitle =    {Proceedings of the 20th European Conference on Genetic
                  Programming, EuroGP 2017},
   ...
}
```
```
@incollection{CarPinOli2017recipe,
...
crossref = "EuroGP2017"
}
```
This is not erroneous since Bibtex ignores the case of citation keys. On the other hand, for LaTeX these keys are case sensitive and this seems the only occasion in the Iridia database that the capitalisation of a key/crossref pair doesn't match, maybe worth changing.

This is not a big deal, of course. I encountered it while testing a function from package `rbibutils`, which currently uses case sensitive comparison to find cross-referenced entries.

**Comment by MLopez-Ibanez** [comment]
Fixed in commit 4831eb078a2c408e52bb9a616dc234907a701e62
